### ISSUE TITLE
yarn zip fails with "Warning: Can not create sync-exec directory Use --force to continue."

### ISSUE THREAD

**Issue by mrcave** [elegantthemes/create-divi-extension#93] opened 2018-06-04 17:18 UTC
Trying to write my first module. Working well in development but tried to deploy production plugin archive with `yarn zip` and got this:

```
yarn run v1.7.0
$ divi-scripts build && divi-scripts zip --force
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  1.19 KB  dpu-page-list/scripts/builder-bundle.min.js
  314 B    dpu-page-list/scripts/frontend-bundle.min.js
  20 B     dpu-page-list/styles/style.min.css

Built the bundle with browser support for >1%, last 4 versions, Firefox ESR, not ie < 11.
Running "makepot:target" (makepot) task


undefined

Running "po2mo:files" (po2mo) task
Warning: Can not create sync-exec directory Use --force to continue.

Aborted due to warnings.
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any idea what might be going wrong? Or where I can investigate further? Thanks!

**Comment by etstaging** [comment] 2018-06-04 17:18
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by lots0logs** [comment] 2018-06-04 17:54
Gettext is needed when running the zip command. Looks like its not installed in the environment you are using. :thinking:

**Comment by mrcave** [comment] 2018-06-04 18:10
Thanks @lots0logs. I'm running Local by Flywheel on Mac. Tried installing gettext via homebrew

```
brew install gettext
brew link --force gettext
```

`yarn zip` got a little further this time (created a POT) but still fails:

```
Built the bundle with browser support for >1%, last 4 versions, Firefox ESR, not ie < 11.
Running "makepot:target" (makepot) task


>> POT file saved to languages/en_US.po

Running "po2mo:files" (po2mo) task
Warning: Can not create sync-exec directory Use --force to continue.

Aborted due to warnings.
error Command failed with exit code 3.
```

**Comment by lots0logs** [comment] 2018-06-04 18:48
AFAICT the issue is that writing to `/tmp` is failing. Could you check to see if the correct permissions are set on that directory?

**Comment by mrcave** [comment] 2018-06-04 18:55
Is that `/tmp` relative to the plugin/script or is it from root?

I tried sudoing and forcing the command `sudo yarn zip --force` (which I would have assumed might trump any permissions issues) but still get the same error.

**Comment by aldorr** [comment] 2018-07-11 10:36
Same here. On  Mac OS 10.13.5
It looks like it tries to write a file called `sync-exec-some_numbers` to the directory `/var/folders/2n/a_bunch_of_characters/T/`
But the script is not permitted to write to that directory.
Unable to change file permissions without logging in as root. Change the tmp directory? I tried to store it in a temp directory in my home directory and it failed with the same error.
My only workaround for now was to build & zip on my linux server.

**Comment by snewsh** [comment] 2019-01-09 15:06
Any advice on this issue yet? I have exactly the same problem as OP. I am stuck without being able to zip

**Comment by lots0logs** [comment] 2019-01-10 16:27
@snewsh Are you using our Divi docker image for development? If not, maybe give it a try and see if you still see this same issue when running the zip command inside the docker container. More details [here](https://www.elegantthemes.com/documentation/developers/divi-development-environment/)

**Comment by snewsh** [comment] 2019-01-10 16:31
No. I've been using Flywheel but I'll give it a try and keep you posted. Thanks for your time.

**Comment by snewsh** [comment] 2019-01-11 10:34
@lots0logs I now have Docker installed with two containers (1 Wordpress & 1 Database). I have a command prompt open inside the container but am unable to use yarn commands. Are there any docs or can you point me in the right direction. Obviously, tried 'Googling". Lots of info for various situations but nothing for this specific issue. Cheers
![screen shot 2019-01-11 at 10 28 10](https://user-images.githubusercontent.com/43791070/51028823-7d1a6f80-158c-11e9-8f52-0650e3b01bc1.png)

**Comment by lots0logs** [comment] 2019-01-11 18:32
What does the error say when you try to use yarn?

**Comment by snewsh** [comment] 2019-01-11 20:11
I've managed to get yarn start to work but it still fails on yarn zip with the same 'Can not create sync-exec directory' error.
![screen shot 2019-01-11 at 20 02 32](https://user-images.githubusercontent.com/43791070/51057246-e7f39700-15dc-11e9-94c8-08162a604b89.png)

**Comment by lots0logs** [comment] 2019-01-11 20:36
Doesnt look like you were inside container when running commands in your screenshot :thinking:

**Comment by lots0logs** [comment] 2019-01-11 20:44
Just to be clear, here is what you need to do:

1. Enter the container by running `docker-compose exec -u 1000 wordpress /bin/bash`
2. Change to your extension directory `cd wordpress/wp-content/plugins/your-extension`
3. Now run whatever yarn commands you need to.

**Comment by snewsh** [comment] 2019-01-11 21:07
@lots0logs Yes, you're correct. I was originally in the container as shown in the previous screenshot but I was doing step 2 before step 1.  Which directory do I run step 1 in? Thanks

**Comment by lots0logs** [comment] 2019-01-11 21:57
You will start out in the directory that has the docker-compose.yml file in it. Then after running the command from the first step you will be in the container and can switch to your plugin directory using the command I provided in step 2.

**Comment by snewsh** [comment] 2019-01-14 10:02
I feel like I've followed the instructions correctly @lots0logs but can't change directory once in the container.
![screen shot 2019-01-14 at 09 58 45](https://user-images.githubusercontent.com/43791070/51106317-5013ca00-17e3-11e9-9bbe-bcc95179efb3.png)
![screen shot 2019-01-14 at 09 59 11](https://user-images.githubusercontent.com/43791070/51106325-5609ab00-17e3-11e9-8926-934cd5b7197c.png)

**Comment by lots0logs** [comment] 2019-01-14 19:04
You need to use the relative path like this:
```
cd wordpress/wp-content/plugins/image_clip
```

**Comment by snewsh** [comment] 2019-01-14 20:48
Thanks @lots0logs. Managed to get yarn start working but unfortunately yarn zip hangs and never completes.
![screen shot 2019-01-14 at 20 46 49](https://user-images.githubusercontent.com/43791070/51140122-a150a780-183d-11e9-9e43-6c0590f3bae7.png)

**Comment by lots0logs** [comment] 2019-01-14 20:59
It can sometimes take a couple minutes to complete. How long did you wait before canceling it?

**Comment by snewsh** [comment] 2019-01-14 21:21
Maybe about 10-15 minutes each time the first couple of times but this time it's been running for over an hour!

**Comment by lots0logs** [comment] 2019-01-14 22:04
Okay, could you try running `yarn install --force` and then try zip again?

**Comment by snewsh** [comment] 2019-01-15 08:10
@lots0logs Sorry but same result!

**Comment by lots0logs** [comment] 2019-01-15 18:03
This issue was fixed by updating one of the dependencies. Running `yarn install --force` will install the updated dependency.

**Closed by lots0logs** 2019-01-15 18:03 UTC
Labels: BUG, COMPATIBILITY
