### ISSUE TITLE
%%order_class%% bug on Custom Post Type

### ISSUE THREAD

**Issue by mrkenng** [elegantthemes/create-divi-extension#190] opened 2018-11-03 10:07 UTC
### Problem Description
When using custom post type with Visual builder, seems like %%order_class%% is generating the wrong css output that causes not to render properly due to that. 

Only custom modules are having this issue. 

e,g 
`.et-db .hello_world_0 #et-boc h1.et_pb_module_header
`
and it should be
`.et-db #et-boc .hello_world_0 h1.et_pb_module_header`

the only custom post type is working is the Divi built-in project which works very well with custom modules which is generating without the .et-db #et-boc

`.hello_world_0 h1.et_pb_module_header
`
Any idea on this?

**Comment by mrkenng** [comment] 2018-11-03 10:54
Also noticed that the style-cpt.css is over writing font sizes on header/title for custom modules.

e.g 

`.et-db #et-boc .et_pb_column_1_3 h1, .et-db #et-boc .et_pb_column_1_4 h1, .et-db #et-boc .et_pb_column_1_5 h1, .et-db #et-boc .et_pb_column_1_6 h1, .et-db #et-boc .et_pb_column_2_5 h1`

**Comment by mrkenng** [comment] 2018-11-05 13:29
Hi @atanas-angelov-dev 

The font field. I tested out I think quite alot of custom modules out there and all of them are having same issue on Custom Post Type. 

`public function get_advanced_fields_config() {
		return array(
			'fonts'      => array(
				'content' => array(
					'label'    => esc_html__( 'Content', 'dsm-supreme-modules-for-divi' ),
					'css'      => array(
						'main' => '%%order_class%% .divi-content',
					),
					'font_size' => array(
						'default'      => '14px',
					),
					'line_height'    => array(
						'default' => '1em',
					),
					'letter_spacing' => array(
						'default' => '0px',
					),
				),
			),
		);
	}`

**Comment by atanas-angelov-dev** [comment] 2018-11-05 13:42
@mrkenng with that snippet the result I get is this:
`.et-db #et-boc .mycm_foobar_module_0 .divi-content`
which is correct (`mycm_foobar_module` is my test `create-divi-extension` module).

Could you please confirm you are on the latest version of the Divi Builder? If yes, then the best course would be to create a minimal repro case - a blank `create-divi-extension` with only enough code to reproduce the issue so that we can investigate.

**Comment by mrkenng** [comment] 2018-11-05 16:06
@atanas-angelov-dev  Take a look at this video https://www.useloom.com/share/7f04cfaace7143a692ed58ea3ec91511
A clean installation of Divi and WordPress as well as the new created plugin from create-divi-extension

I'm using a quick method to create custom post type using a plugin for this purpose.

[helloworld.zip](https://github.com/elegantthemes/create-divi-extension/files/2549466/helloworld.zip)

Attached is the both JSX and PHP.

**Comment by atanas-angelov-dev** [comment] 2018-11-06 13:57
I was able to reproduce the issue now so I'm marking this as a bug - thanks @mrkenng !

<details>
 <summary>Developer Notes</summary>
<code>$outside_builder</code> in PHP (there's an equivalent variable in JSX) incorrectly matches the order class as outside of the builder when prefixing selectors.
</details>

**Comment by mrkenng** [comment] 2018-11-07 05:13
Thanks! Hope to see this fixed in upcoming version or next 😀

**Comment by mrkenng** [comment] 2019-05-29 10:12
Hello @atanas-angelov-dev Just wonder if there's any update on this? Recently, i found out that using non-divi theme with Divi Builder plugin have such issue as well.

**Comment by mrkenng** [comment] 2019-11-13 13:52
any good news for this? The new Theme builder is having this issue as well.

**Comment by mrkenng** [comment] 2020-08-10 06:42
Hi guys! Any update on this? It been a while. Can't wait for the fix 👍

**Comment by ayubadiputra** [comment] 2020-08-27 08:48
Hi @mrkenng @VladET I think the issue above happened because the fields definitions you shared above uses `et_pb_*` class as the selector. The builder considers it as part of the official module and marks it as an `inside` element. It causes the Hello World module class is classified as an `outside` element, and prepend it before `#et-boc`. If you replace `et_pb_module_header` with another class name, the problem is solved.

However, we will find a way how to resolve this on our end to avoid similar issue happen again in the future.

**Comment by ayubadiputra** [comment] 2020-11-03 17:23
This one already addressed.

**Closed by ayubadiputra** 2020-11-03 17:23 UTC
Labels: !IMPORTANT, BUG, PRIORITY: LOW
