### ISSUE TITLE
VB Support partial not working in custom module

### ISSUE THREAD

**Issue by SatishKumarPrajapati** [elegantthemes/create-divi-extension#104] opened 2018-06-08 14:08 UTC
### Problem Description
I am trying to get server side data and use $vb_support = 'partial' but it is not working. I am using the code below and i get output on front hand but not able to to partial data on builder mode.

### Steps To Reproduce
1. use this code in render 
$final_post_types = array();
        $all_post_types = get_post_types(array('public' => true), $output);

        $skip_post_types = array(
            'attachment',
        );

        if($output === 'names'){
            return array_diff($all_post_types,$skip_post_types);
        }

        foreach($all_post_types as $name => $post_type){
            if(!in_array($name,$skip_post_types)){
                $final_post_types[$name] = $post_type->label;
            }
        }

        echo $final_post_types;

Is there any solution for this

**Comment by etstaging** [comment] 2018-06-08 14:08
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [x] Detailed description
- [x] Steps to reproduce included
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by lots0logs** [comment] 2018-06-10 23:02
Hi! We'll need to see more of the code, preferably the entire module in order to advise you on the issue.

**Comment by SatishKumarPrajapati** [comment] 2018-06-11 11:08
Hello this is new separate code for your test.
In this code i am getting list of post on base of category.

`<?php
class BPD_Test extends ET_Builder_Module
{

    public $slug = 'bpd_test';
    public $vb_support = 'partial';

    public function init()
    {
        $this->name = esc_html__('Test Control', 'bpd-booster-pack-divi');

    }
    public function get_fields()
    {
        return array(
            'post_category' => [
                'label'           => esc_html__( 'Meta Data', 'bpd-booster-pack-divi' ),
                'type'            => 'categories',
                'taxonomy_name'   => 'category',
                'toggle_slug'     => 'layout_settings',
            ],
        );
    }
    function render_prop( $value = '', $field_name = '', $field_type = '', $render_slug = '') {
        $order_class = self::get_module_order_class( $render_slug );
        $output      = '';

        if ( '' === $value ) {
            return $output;
        }

        $option_search  = array( '&#91;', '&#93;' );
        $option_replace = array( '[', ']' );

        switch ( $field_type ) {
            case 'options_list_checkbox':
                $checkboxes = '';
                $value          = str_replace( $option_search, $option_replace, $value );
                $value          = json_decode( $value );
                $checkbox_name  = sprintf( '%1$s_%2$s', $order_class, $field_name );

                foreach ( $value as $index => $option ) {
                    $checkbox_id  = sprintf( '%1$s_checkbox_%2$s', $checkbox_name, $index );
                    $is_checked   = 1 === $option->checked ? true : false;
                    $option_value = wp_strip_all_tags( $option->value );

                    $checkboxes .= sprintf(
                        '<span class="checkbox-wrap">
							<input type="checkbox" id="%1$s" class="input" value="%2$s"%3$s>
							<label for="%1$s"><i></i>%2$s</label>
						</span>',
                        esc_attr( $checkbox_id ),
                        esc_attr( $option_value ),
                        $is_checked ? ' checked="checked"' : ''
                    );
                }

                $output = $checkboxes;
                break;
            default:
                $output = $value;
                break;
        }

        return $output;
    }

    public function render( $attrs, $content = null, $render_slug ) {

        $args = array( 'posts_per_page' => 5,'category' => $this->props['post_category']);

        $myposts = get_posts( $args );
        echo "<div><ul>";
        foreach ( $myposts as $post ) : setup_postdata( $post ); ?>
            <li>
                <a href="<?php echo get_the_permalink($post->ID); ?>"><?php echo get_the_title($post->ID); ?></a>
            </li>
        <?php endforeach;
        echo "</ul></div>";
                wp_reset_postdata();
    }
}

new BPD_Test;
`

**Comment by jking2076** [comment] 2018-06-14 18:39
what was the answer?

**Comment by SatishKumarPrajapati** [comment] 2018-06-15 06:35
@jking2076 no answer yet, I am also waiting for answer.

**Comment by bdombro** [comment] 2018-08-14 16:56
I'm new here. What does partial mean, anyways? I know that doesn't help answer your question, but I'd appreciate the tip! I don't see any mention of partial in the docs.

**Comment by lots0logs** [comment] 2018-08-14 17:36
This issue has been fixed in the latest version of Divi :smiley: 

@bdombro You can learn about it [here](https://www.elegantthemes.com/documentation/developers/divi-module/compatibility-levels/).

**Comment by jking2076** [comment] 2018-08-14 17:36
instead of full or "on" compatibility ( https://www.elegantthemes.com/documentation/developers/divi-module/compatibility-levels/ ), you can specify "partial" and not rely on jsx to render modules in VB. This mechanism uses ajax to render every change to options.

**Comment by jking2076** [comment] 2018-08-14 17:40
yes, it has been fixed and I am ecstatic!  Some conversions of older modules would be almost impossible, so this is good.  I hope partial is not done away with.  Creating new modules with jsx is the way to go as long as they are not complex, IMO.

**Comment by lots0logs** [comment] 2018-08-14 18:03
@SatishKumarPrajapati Could you check to see if the issue is still present with the latest version of Divi?

**Comment by SatishKumarPrajapati** [comment] 2018-08-16 07:12
@lots0logs issue has been solved with latest version.

**Closed** 2018-08-16 07:58 UTC
Labels: ANSWERED
