### ISSUE TITLE
yarn zip error on Flywheel Local

### ISSUE THREAD

**Issue by SJ-James** [elegantthemes/create-divi-extension#38] opened 2018-04-27 10:03 UTC
### Problem Description
When using yarn commands from command line on Windows 10 / Flywheel Local install - 
yarn start, yarn build both work, yarn zip fails with "error Command failed with exit code 1." Ran the same command on two install twice and same error. 

npm run zip doesn't seem to work either. throws the following errors: 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-extension@0.1.0 zip: `divi-scripts build && divi-scripts zip`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-extension@0.1.0 zip script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### Steps To Reproduce
1. npx create-divi-extension my-extension
2. yarn start
3. yarn zip

### Screenshot and/or gif
![image](https://user-images.githubusercontent.com/18221395/39356781-d1e85fa4-4a08-11e8-80a0-0ac8f20b4df6.png)

**Comment by etstaging** [comment] 2018-04-27 10:03
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [x] Detailed description
- [x] Steps to reproduce included
- [ ] Support Ticket URL included
- [x] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by VladET** [comment] 2018-04-27 11:49
@SJ-James We are aware of this. Closing in favor of https://github.com/elegantthemes/create-divi-extension/issues/22

**Closed by VladET** 2018-04-27 11:49 UTC

**Comment by SJ-James** [comment] 2018-04-27 12:41
Thanks @VladET
